### ISSUE TITLE
Derivatives conceptually

### ISSUE THREAD

**Issue by preethampython101** [hakancangunerli/calcMachine#2]
You seem to have an upper and lower bound, which I don't think is necessary. Derivatives are not areas, or "compound" parts, do they are generally not computed over a range. Make sure to change the 2 inputs to 1 and only take the specific "point" the users wants the derivative at.

**Comment by hakancangunerli** [comment]
hey,

the bound is for matplotlib to graph the location since i can't know how big the graph is by user's input :)

thanks for bringing it up!
